# Generated by Django 5.2.4 on 2025-08-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_count", models.PositiveIntegerField()),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
            ],
        ),
    ]
