# Generated by Django 5.2.4 on 2025-08-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="popularity",
            field=models.PositiveIntegerField(
                default=0, help_text="Increments every time when product is purchased"
            ),
        ),
    ]
